models.py
from app import db
from datetime import datetime
#import re
from slugify import slugify


# s - заголовок поста - строка (pythex.org)
# выделение ненужных символов и их замена на '-'

#def slugify(s):
	# pattern = r'[^\w+]'
	# return re.sub(pattern, '-', s)
	

class Post(db.Model):
	# свойства
	id = db.Column(db.Integer, primary_key=True)
	title = db.Column(db.String(140))
	slug = db.Column(db.String(140), unique=True)
	body = db.Column(db.Text)
	created = db.Column(db.DateTime, default=datetime.now())


	# конструктор
	def __init__(self, *args, **kwargs):
		# конструктор класса предка
		super(Post, self).__init__(*args, **kwargs)
		self.generate_slug()


	def generate_slug(self):
		# url генерируется из текста заголовка - 'slugify'
		if self.title:
			self.slug = slugify(self.title)


	def __repr__(self):
		return '<Post id: {}, title: {}>'.format(self.id, self.title)



class Tag(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	name = db.Column(db.String(100))
	slug = db.Column(db.String(100))

	def __init__(self, *args, **kwargs):
		super(Tag, self).__init__(*args, **kwargs)
		self.slug = slugify(self.name)

	def __repr__(self):
		return '<Tag id: {}, name: {}>'.format(self.id, self.title)

app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy

from flask_migrate import Migrate, MigrateCommand
#from flask_script import Manager


app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)


migrate = Migrate(app, db)
#manager = Manager(app)
#manager.add_command('db', MigrateCommand)

main.py
from app import app
from app import db

from posts.blueprint import posts

import view


app.register_blueprint(posts, url_prefix='/blog')


if __name__ == '__main__':
	app.run()

posts/blueprint.py
from flask import Blueprint
from flask import render_template

from models import Post

posts = Blueprint('posts', __name__, template_folder='templates') # posts - название блюпринта, первый аргумент передается в base.html для создания ссылки


@posts.route('/')
def index(): # название передается в url_for в базовом шаблоне
	posts = Post.query.all()
	return render_template('posts/index.html', posts=posts)

# http://localhost/blog/first-post (slug='first post')
@posts.route('/<slug>')
def post_detail(slug):
	post = Post.query.filter(Post.slug==slug).first()
	return render_template('posts/post_detail.html', post=post)

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
	<title>

		{% block title %}

		{% endblock %} | Flask app

	</title>
</head>
<body>

<nav class="navbar navbar-expand-lg bg-warning">
		<div class="container-fluid">
			<a class="navbar-brand" href=" {{ url_for('index') }} ">Flask</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">

					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href=" {{ url_for('posts.index') }} ">Blog</a>
					</li>

					<li class="nav-item">
						<a class="nav-link" href="#">Link</a>
					</li>
					
					<li class="nav-item">
						<a class="nav-link disabled" aria-disabled="true">Disabled</a>
					</li>
				</ul>
				<form class="d-flex" role="search">
					<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
					<button class="btn btn-outline-success" type="submit">Search</button>
				</form>
			</div>
		</div>
	</nav>

	<div class="container">
		<div class="row">
			<h1>
				{% block content_title %}

				{% endblock %}
			</h1>

			{% block content %}

			{% endblock %}

		</div>
	</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}

	Index page

{% endblock %}

{% block content_title %}
	Index page
{% endblock %}

{% block content %}
 	Some content
{% endblock %}